# <center> Création et résolution de labyrinthes</center>

**<center>JONUZI Arbër & PAYRAUDEAU Alix</center>**

## 1) Introduction

### 1.2. Grille

In [1]:
########
class UneCellule:
    """
    définition d'une cellule
    """
    
    def __init__(self,x, y):
        """
        créer une cellule positionnée en (x=ligne, y=colonne)
        """
        
        self.x = x
        self.y = y
        #les murs sont dans l'ordre : N, S, E, O. 
        #la valeur est à True si un mur est présent, False sinon
        self.murs = {'N': True, 'S': True, 'E': True, 'O': True}

########       
class Grille :
    """
    construction d'une grille de cellules
    """
    
    def __init__(self, nl, nc):
        """
        construction d'une grille de dimension (nl, nc)
        """
        
        self.nl = nl
        self.nc = nc
        self.cadrillage = []
        for i in range(nl):
            GrilleLigne=[]
            for j in range(nc):
                GrilleLigne.append(UneCellule(i,j))
            self.cadrillage.append(GrilleLigne)
        
        
    def cellule(self, x, y):
        """
        retourne la cellule de la grille de position (x=ligne, y=colonne)
        """
        
        return self.cadrillage[x][y]
    
    def __str__(self):
        """
        retourne une chaine de caractères représentant le labyrinthe
        pour les cellules touchant le bord gauche ou le bord du haut de la grille, les 4 murs sont représentés.
        pour les autres, seuls les murs Est et Sud sont représentés
        """
        
        laby_lignes = []
        laby_l = ['+']
        for y in range(self.nc):
            if self.cadrillage[0][y].murs['N']:
                laby_l.append('---+')
            else :
                laby_l.append('   +')
        laby_lignes.append(''.join(laby_l))
                              
              
        for x in range(0,self.nl):
            if self.cadrillage[x][0].murs['O'] :
                laby_l = ['|']
            else :
                laby_l = [' ']
            for y in range(self.nc):
                if self.cadrillage[x][y].murs['E']:
                    laby_l.append('   |')
                else:
                    laby_l.append('    ')
            laby_lignes.append(''.join(laby_l))
            laby_l = ['+']
            for y in range(self.nc):
                if self.cadrillage[x][y].murs['S']:
                    laby_l.append('---+')
                else:
                    laby_l.append('   +')
            laby_lignes.append(''.join(laby_l))
        
        #laby_lignes.append('\n')
        return '\n'.join(laby_lignes)

### 1.3. Utilisation des classes

In [2]:
grilleTest = Grille(4,6)
print(grilleTest)
# Accès aux dimensions de la grille
print(grilleTest.nl, grilleTest.nc)
# Accès à une cellule de la grille
cell =grilleTest.cellule(2,3)
# Accès à la position d'une cellule (sous forme (ligne, colonne))
print(cell.x, cell.y)
# Accès aux murs d'une cellule
cell.murs
# Accès au mur Est d'une cellule
cell.murs['E']

+---+---+---+---+---+---+
|   |   |   |   |   |   |
+---+---+---+---+---+---+
|   |   |   |   |   |   |
+---+---+---+---+---+---+
|   |   |   |   |   |   |
+---+---+---+---+---+---+
|   |   |   |   |   |   |
+---+---+---+---+---+---+
4 6
2 3


True

In [3]:
# Détruisons le mur Est de la cellule 'cell' positionnée en (2,3)
cell.murs['E']=False
print(grilleTest)

+---+---+---+---+---+---+
|   |   |   |   |   |   |
+---+---+---+---+---+---+
|   |   |   |   |   |   |
+---+---+---+---+---+---+
|   |   |   |       |   |
+---+---+---+---+---+---+
|   |   |   |   |   |   |
+---+---+---+---+---+---+


In [4]:
grilleTest.cellule(2,4).murs['O']

True

In [5]:
grilleTest.cellule(2,3).murs['E']=True
grilleTest.cellule(2,4).murs['O']=False
print(grilleTest)
# Est et Sud d'une cellule sont traçés

+---+---+---+---+---+---+
|   |   |   |   |   |   |
+---+---+---+---+---+---+
|   |   |   |   |   |   |
+---+---+---+---+---+---+
|   |   |   |   |   |   |
+---+---+---+---+---+---+
|   |   |   |   |   |   |
+---+---+---+---+---+---+


In [6]:
# casser le mur Nord de (2,3) passera inaperçu
grilleTest = Grille(4,6)
grilleTest.cellule(2,3).murs['N']=False
print(grilleTest)

+---+---+---+---+---+---+
|   |   |   |   |   |   |
+---+---+---+---+---+---+
|   |   |   |   |   |   |
+---+---+---+---+---+---+
|   |   |   |   |   |   |
+---+---+---+---+---+---+
|   |   |   |   |   |   |
+---+---+---+---+---+---+


In [7]:
# si on veut voir disparaitre le mur, il faut détruire le mur Sud de (1,3)
grilleTest.cellule(1,3).murs['S']=False
print(grilleTest)

+---+---+---+---+---+---+
|   |   |   |   |   |   |
+---+---+---+---+---+---+
|   |   |   |   |   |   |
+---+---+---+   +---+---+
|   |   |   |   |   |   |
+---+---+---+---+---+---+
|   |   |   |   |   |   |
+---+---+---+---+---+---+


### 1.4. Exercice effaceMur() : Premier exercice

Afin de palier au problème évoqué plus haut, créer une fonction `effaceMur(grille, coord, orientation)` qui pour une grille grille :

* efface le mur `orientation` (c-à-d 'N', 'S', 'E' ou 'O') de la cellule de position `coord`

* efface aussi le mur correspondant de la cellule voisine.

In [8]:
def effaceMur(grille, coord : tuple, orientation) :
    if (coord[0] == 0 and orientation == 'N') or (coord[1] == 0 and orientation == 'O') or (coord[0] == grille.nl-1 and orientation == 'S') or (coord[1] == grille.nc-1 and orientation == 'E'):
        grille.cellule(coord[0],coord[1]).murs[orientation]=False
    else :  
        grille.cellule(coord[0],coord[1]).murs[orientation]=False
        if orientation == 'N':
            grille.cellule(coord[0]-1,coord[1]).murs['S']=False
        if orientation == 'E':
            grille.cellule(coord[0],coord[1]+1).murs['O']=False 
        if orientation == 'S':
            grille.cellule(coord[0]+1,coord[1]).murs['N']=False 
        if orientation == 'O':
            grille.cellule(coord[0],coord[1]-1).murs['E']=False

**Tests effaceMur() :**

In [9]:
grilleTest = Grille(5,7)
effaceMur(grilleTest, (4,6),'E')
print(grilleTest)

+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+
|   |   |   |   |   |   |    
+---+---+---+---+---+---+---+


In [10]:
grilleTest = Grille(4,6)

# on efface le mur Ouest de la cellule (3,2)
effaceMur(grilleTest,(3,2),'O')

# affichage de la cellule modifiée
print('(3,2) :',grilleTest.cellule(3,2).murs)

# affichage de la cellule 'voisine', ici la cellule (3,1)
print('(3,1) :',grilleTest.cellule(3,1).murs)

# affichage de la grille
print(grilleTest)

(3,2) : {'N': True, 'S': True, 'E': True, 'O': False}
(3,1) : {'N': True, 'S': True, 'E': False, 'O': True}
+---+---+---+---+---+---+
|   |   |   |   |   |   |
+---+---+---+---+---+---+
|   |   |   |   |   |   |
+---+---+---+---+---+---+
|   |   |   |   |   |   |
+---+---+---+---+---+---+
|   |       |   |   |   |
+---+---+---+---+---+---+


In [11]:
grilleTest = Grille(4,6)

# on efface le mur Nord de la cellule (2,1)
effaceMur(grilleTest,(2,1),'N')

# affichage de la cellule modifiée
print('(2,1) :',grilleTest.cellule(2,1).murs)

# affichage de la cellule 'voisine', ici la cellule (1,1)
print('(1,1) :',grilleTest.cellule(1,1).murs)

# affichage de la grille
print(grilleTest)

(2,1) : {'N': False, 'S': True, 'E': True, 'O': True}
(1,1) : {'N': True, 'S': False, 'E': True, 'O': True}
+---+---+---+---+---+---+
|   |   |   |   |   |   |
+---+---+---+---+---+---+
|   |   |   |   |   |   |
+---+   +---+---+---+---+
|   |   |   |   |   |   |
+---+---+---+---+---+---+
|   |   |   |   |   |   |
+---+---+---+---+---+---+


In [12]:
grilleTest = Grille(4,6)

# on efface le mur Est de la cellule (0,5)
effaceMur(grilleTest,(0,5),'E')

# affichage de la cellule modifiée
print('(0,5) :',grilleTest.cellule(0,5).murs)

# Attention : cette cellule n'a pas de cellule voisine située à sa droite, donc il ne doit pas y avoir de modifications supplémentaires !

# affichage de la grille
print(grilleTest)

(0,5) : {'N': True, 'S': True, 'E': False, 'O': True}
+---+---+---+---+---+---+
|   |   |   |   |   |    
+---+---+---+---+---+---+
|   |   |   |   |   |   |
+---+---+---+---+---+---+
|   |   |   |   |   |   |
+---+---+---+---+---+---+
|   |   |   |   |   |   |
+---+---+---+---+---+---+


## 2) Construction de labyrinthes parfaits

In [13]:
import random

### 2.1. Exercice arbreBinaire() :
    
Construire une fonction `arbreBinaire(grille)` qui retourne un labyrinthe créé par l'algorithme suivant :

* on part d'une grille où tous les murs existent.
* on parcourt une à une toutes les cellules de la grille (en commençant en haut à gauche, c'est à dire en (0,0)).
* pour chaque cellule ainsi parcourue, on détruit aléatoirement soit le mur Sud soit le mur Est (en utilisant la fonction `effaceMur`).
* On fera attention que si une cellule est située sur le bord droit de la grille, c'est le mur Sud qui sera détruit.
* De même, si une cellule est située sur le bord du bas de la grille, c'est forcément le mur Est qui sera détruit.
* on ne détruira aucun mur de la cellule située tout en bas à droite.

**Algorithme de l'arbre binaire :**

In [14]:
def arbreBinaire(grille) :
    for i in range(grille.nl):
        for j in range(grille.nc):
            if j == grille.nc-1 :
                sup = 'S'
            elif i == grille.nl-1 :
                sup = 'E'
            elif i != grille.nl-1 and j != grille.nc-1:
                sup =  random.choice(['S', 'E'])
            if i != grille.nl-1 or j != grille.nc-1: 
                effaceMur(grille, (i,j), sup)
    return grille

**Tests de l'Algorithme de l'arbre binaire**

In [15]:
ab = Grille(4,6)
print(arbreBinaire(ab))

+---+---+---+---+---+---+
|       |           |   |
+---+   +---+---+   +   +
|   |           |   |   |
+   +---+---+   +   +   +
|       |               |
+---+   +---+---+---+   +
|                       |
+---+---+---+---+---+---+


**Qu'ont en commun tous ces labyrinthes ?** 

Peu importe le labyrinthe, celui-ci aura toutes ces cellules accessibles depuis l'intérieur.

### 2.2. Exercice sidewinder() :

Construire une fonction sidewinder(grille) qui réalise l'algorithme suivant :

Le labyrinthe est généré une ligne à la fois : pour chaque cellule de cette ligne, on décide aléatoirement s'il faut détruire le mur Est ou pas.

* Si oui, alors on détruit le mur Est.
* Sinon, on considère le passage horizontal qui vient d'être terminé, formé par la cellule actuelle et toutes les cellules à gauche qui ont creusé des passages menant à celle-ci. On choisit alors aléatoirement une cellule le long de ce passage et on détruit son mur Sud.

**Algorithme sidewinde :**

In [16]:
def sidewinder(grille) :
    for i in range(grille.nl):
        compt = 0
        for j in range(grille.nc):
            b = random.randint(0, 1)
            if (i == grille.nl-1 and j != grille.nc-1):
                effaceMur(grille, (i,j), 'E')
            elif (j != grille.nc-1) and b == 0:
                effaceMur(grille, (i,j), 'E')
                compt += 1
            elif (i != grille.nl-1):
                effaceMur(grille, (i,random.randint(j-compt,j)), 'S')
                compt = 0
    return grille

**Tests de l'Algorithme sidewinde :**

In [17]:
SW = Grille(6,6)
print(sidewinder(SW))

+---+---+---+---+---+---+
|   |               |   |
+   +---+---+   +---+   +
|               |   |   |
+---+---+---+   +   +   +
|                   |   |
+---+   +---+---+---+   +
|       |       |       |
+---+   +   +---+   +---+
|           |   |   |   |
+---+   +---+   +   +   +
|                       |
+---+---+---+---+---+---+


### 2.3. Exercice explorationE() :

```
definition de explorationE(grille)

Visite = tableau 2D (ou matrice ...) de même taille que la grille.
Ce tableau nous servira à savoir si une cellule a déja été traitée ou non

Pile = une liste, vide pour l'instant

On choisit aléatoirement une cellule, sous forme d'un couple (ligne, colonne)
On la met dans Pile, et on indique dans le tableau Visite que cette cellule a été traitée.

tant que Pile non vide
  soit (i,j) le premier élément de Pile
  on recherche les voisins non encore traités de (i,j)

  si il y en a
      soit (k,l) = un de ces voisins, choisi au hasard 
      on détruit le mur entre (k,l) et la cellule (i,j)
      on indique dans Visite que (k,l) a été traitée
      on ajoute (k,l) au début de Pile
  sinon
      on retire le premier élément de Pile

retourner grille
```

**Fonctions annexes :**

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**voisins() :**

retourne la liste des voisins d'une cellule

In [18]:
def voisins(grille, coord):
    x=coord[0]
    y=coord[1]
    Voisins = [(x+1,y),(x-1,y),(x,y+1),(x,y-1)]
    if y == 0:
        del Voisins[3]
    if y == grille.nc-1:
        del Voisins[2]
    if x == 0:
        del Voisins[1]
    if x == grille.nl-1:
        del Voisins[0]
    return Voisins

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**visiter() :**

retourne le tableau 2D (ou matrice ...) de même taille que la grille avec que des `False`

In [19]:
def visiter(grille):
    Visite = []
    for i in range(grille.nl):
        lst=[]
        for j in range(grille.nc):
            lst.append(False)
        Visite.append(lst)
    return Visite

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**murEntreCellules() :**

retourne le mur entre deux cellules voisines

In [20]:
def murEntreCellules(cellule, voisin) :
    if cellule[0]-voisin[0]<0 :
        mur = 'S'
    if cellule[0]-voisin[0]>0 :
        mur = 'N'
    if cellule[1]-voisin[1]<0 :
        mur = 'E'
    if cellule[1]-voisin[1]>0 :
        mur = 'O'
    return mur

**Algorithme d'exploration exhaustive :**

In [21]:
def explorationE(grille) :
    Visite = visiter(grille)
    Pile = []
    cellule = (random.randint(0,grille.nl-1), random.randint(0,grille.nc-1))
    Pile.append(cellule)
    Visite[cellule[0]][cellule[1]] = True
    
    while Pile != []:
        cellule = Pile[0]
        Voisins = voisins(grille,cellule)
        
        for i in range(len(Voisins)-1,-1,-1):
            if Visite[Voisins[i][0]][Voisins[i][1]] == True:
                del Voisins[i]
                
        if Voisins != [] :
            randCell = Voisins[random.randint(0,len(Voisins)-1)]
            mur = murEntreCellules(cellule, randCell)
            effaceMur(grille, cellule, mur)
            Visite[randCell[0]][randCell[1]] = True
            Pile.insert(0,randCell)
        else :
            del Pile[0]
            
    return grille

**Tests de l'Algorithme d'exploration exhaustive :**

In [22]:
grilleTest = Grille(4,6)
exp = explorationE(grilleTest)
print(exp)

+---+---+---+---+---+---+
|   |       |           |
+   +   +   +   +---+   +
|       |   |       |   |
+   +---+   +   +   +---+
|   |   |   |   |       |
+   +   +---+---+---+   +
|                       |
+---+---+---+---+---+---+


### 2.4. Bonus

Proposer une fonction `fusion(grille)` qui construit un labyrinthe parfait sur ce principe : [lien](https://fr.wikipedia.org/wiki/Mod%C3%A9lisation_math%C3%A9matique_d%27un_labyrinthe#Fusion_al%C3%A9atoire_de_chemins)

In [23]:
#retourne une matrice de meme taille que grille avec cases numérotées
def positionGrille(grille):
    Pos = []
    compt = 0
    for i in range(grille.nl):
        lst=[]
        for j in range(grille.nc):
            lst.append(compt)
            compt+=1
        Pos.append(lst)
    return Pos

In [24]:
def fusion(grille):
    position = positionGrille(grille)
    nbMurOuvert = 0
    
    while(nbMurOuvert<grille.nl*grille.nc-1):
        
        cellule = (random.randint(0,grille.nl-1), random.randint(0,grille.nc-1))
        Voisins = voisins(grille,cellule)
        
        for i in range(len(Voisins)-1,-1,-1):
            if position[Voisins[i][0]][Voisins[i][1]] == position[cellule[0]][cellule[1]]:
                del Voisins[i]
        
        if Voisins != [] :
            randCell = Voisins[random.randint(0,len(Voisins)-1)]
            mur = murEntreCellules(cellule, randCell)
            effaceMur(grille, cellule, mur)
            nbMurOuvert+=1
            num = position[randCell[0]][randCell[1]]
            
            for i in range(len(position)):
                for j in range(len(position[0])): 
                    if position[i][j] == num:
                        position[i][j] = position[cellule[0]][cellule[1]]
                        
    return grille            

In [25]:
grilleTestFus = Grille(7,10)
fus = fusion(grilleTestFus)
print(fus)

+---+---+---+---+---+---+---+---+---+---+
|       |       |   |   |           |   |
+   +---+---+   +   +   +   +   +---+   +
|   |       |   |       |   |           |
+   +---+   +   +---+   +---+   +---+   +
|       |               |       |       |
+---+   +   +---+---+   +---+   +---+   +
|               |       |   |   |       |
+---+   +---+---+   +   +   +   +---+   +
|           |   |   |   |       |       |
+   +   +   +   +   +---+   +---+   +---+
|   |   |   |       |   |       |       |
+---+---+   +---+---+   +   +---+---+   +
|                                   |   |
+---+---+---+---+---+---+---+---+---+---+


## 3) Résolution d'un labyrinthe parfait

### 3.1. Exercice attenantes() : Introduction

In [26]:
laby = explorationE(Grille(5,7))
effaceMur(laby,(0,0),'O')
effaceMur(laby,(4,6),'E')
print(laby)

+---+---+---+---+---+---+---+
    |       |               |
+   +---+   +   +   +---+   +
|       |       |   |       |
+---+   +---+   +   +   +---+
|   |       |   |   |   |   |
+   +---+   +---+   +   +   +
|           |       |       |
+   +---+---+   +---+---+   +
|               |            
+---+---+---+---+---+---+---+


Construire une fonction `attenantes(labyrinthe,coord)` qui retourne les cellules attenantes à la cellule de position `coord`.

In [27]:
def attenantes(labyrinthe, coord):
    lst = []
    cell = labyrinthe.cellule(coord[0],coord[1])
    murs = cell.murs
    if murs['N'] == False:
        nord = (coord[0]-1, coord[1])
        if coord[0]-1 >= 0:
            lst.append(nord)
    if murs['S'] == False:
        sud = (coord[0]+1, coord[1])
        if coord[0]+1 >= 0:
            lst.append(sud)
    if murs['E'] == False:
        est = (coord[0], coord[1]+1)
        if coord[1]+1 <= labyrinthe.nc-1:
            lst.append(est)
    if murs['O'] == False:
        ouest = (coord[0], coord[1]-1)
        if coord[1]-1 >= 0:
            lst.append(ouest)
    return lst

**Tests :**

In [28]:
print(attenantes(laby,(1,3)))

[(0, 3), (2, 3), (1, 2)]


In [29]:
print(attenantes(laby,(1,1)))

[(2, 1), (1, 0)]


### 3.2. Exercice distance() : Calcul des distances depuis (0,0)

In [30]:
import numpy as np
from math import inf

Construire une fonction `distance(labyrinthe)` qui retourne la matrice D pour un `labyrinthe` donné

In [31]:
def distance(labyrinthe):
    D = np.zeros((labyrinthe.nl, labyrinthe.nc))
    for i in range(len(D)):
        for j in range(len(D[i])):
            D[i][j] = inf
    File = []
    
    D[0,0] = 0
    File.append((0,0))
    
    while File != []:
        cell = File[0]
        Attenantes = attenantes(labyrinthe, cell)

        for i in range(len(Attenantes)-1,-1,-1):
            if D[Attenantes[i][0]][Attenantes[i][1]] != inf:
                del Attenantes[i]
                
        if Attenantes != []:
            for i in Attenantes:
                File.append(i)
                D[i[0]][i[1]] = D[cell[0], cell[1]] + 1
        del File[0]
    return D

**Tests :**

In [32]:
print(laby)

+---+---+---+---+---+---+---+
    |       |               |
+   +---+   +   +   +---+   +
|       |       |   |       |
+---+   +---+   +   +   +---+
|   |       |   |   |   |   |
+   +---+   +---+   +   +   +
|           |       |       |
+   +---+---+   +---+---+   +
|               |            
+---+---+---+---+---+---+---+


In [33]:
print(distance(laby))

[[ 0. 21. 20. 17. 16. 17. 18.]
 [ 1.  2. 19. 18. 15. 20. 19.]
 [ 8.  3.  4. 19. 14. 21. 24.]
 [ 7.  6.  5. 12. 13. 22. 23.]
 [ 8.  9. 10. 11. 26. 25. 24.]]


### 3.3. Exercice resolution() :

Construire une fonction `resolution(labyrinthe)` qui retourne le chemin permettant de résoudre le labyrinthe.

In [34]:
def resolution(labyrinthe):
    dist = distance(labyrinthe)
    derCase = (labyrinthe.nl-1, labyrinthe.nc-1)
    
    solution = []
    solution.append(derCase)
    caseNum = dist[solution[0][0]][solution[0][1]]
    
    while int(caseNum) != 0:
        Voisins = voisins(labyrinthe, solution[0])
        for i in range(len(Voisins)):
            if dist[Voisins[i]] == caseNum -1:
                solution.insert(0, Voisins[i])
                caseNum = dist[Voisins[i]]
    return solution

**Tests :**

In [35]:
print(laby,'\n')
print(resolution(laby))

+---+---+---+---+---+---+---+
    |       |               |
+   +---+   +   +   +---+   +
|       |       |   |       |
+---+   +---+   +   +   +---+
|   |       |   |   |   |   |
+   +---+   +---+   +   +   +
|           |       |       |
+   +---+---+   +---+---+   +
|               |            
+---+---+---+---+---+---+---+ 

[(0, 0), (1, 0), (1, 1), (2, 1), (2, 2), (3, 2), (3, 1), (3, 0), (4, 0), (4, 1), (4, 2), (4, 3), (3, 3), (3, 4), (2, 4), (1, 4), (0, 4), (0, 5), (0, 6), (1, 6), (1, 5), (2, 5), (3, 5), (3, 6), (4, 6)]
